//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by gpuPeopsOpenGL.rc
//
#define IDS_INFO0                       1
#define IDS_INFO1                       2
#define IDS_INFO2                       3
#define IDC_DEFAULT                     3
#define IDS_INFO3                       4
#define IDS_INFO4                       5
#define IDS_INFO5                       6
#define IDS_INFO6                       7
#define IDS_INFO7                       8
#define IDS_INFO8                       9
#define IDS_INFO9                       10
#define IDC_DEF1                        127
#define IDC_DEF2                        128
#define IDD_DIALOG_ABOUT                129
#define IDD_CFGDLG                      130
#define IDD_FIXES                       134
#define IDB_GPU                         135
#define IDD_KEYS                        138
#define IDC_TEXWINDOWS                  1001
#define IDC_TEXFIX                      1002
#define IDC_TEXLINEAR                   1003
#define IDC_RESOLUTION                  1004
#define IDC_DRAWDITHER                  1005
#define IDC_CACHESIZE                   1006
#define IDC_BLUR                        1007
#define IDC_CACHETXT                    1008
#define IDC_SSAVE                       1009
#define IDC_USELINES                    1010
#define IDC_COLORDEPTH                  1011
#define IDC_CHANGEDESK                  1012
#define IDC_VSYNC                       1012
#define IDC_USELIMIT                    1013
#define IDC_FRAMELIMIT                  1014
#define IDC_FRAMEAUTO                   1015
#define IDC_FRAMEMANUELL                1016
#define IDC_ADVBLEND                    1017
#define IDC_OFFSCREEN                   1018
#define IDC_OPAQUE                      1019
#define IDC_TEXQUALITY                  1020
#define IDC_USESKIP                     1021
#define IDC_DISPMODE1                   1022
#define IDC_DISPMODE2                   1023
#define IDC_SUBCACHE                    1024
#define IDC_VRAMSIZE                    1025
#define IDC_WINDOWFREE                  1026
#define IDC_EXTCOLCHECK                 1027
#define IDC_FRAMETEX                    1028
#define IDC_WINDOWAUTO                  1029
#define IDC_USETEXPRIO                  1030
#define IDC_SHOWFPS                     1031
#define IDC_WINX                        1032
#define IDC_WINY                        1033
#define IDC_FILTERTYPE                  1034
#define IDC_USEANTIALIAS                1035
#define IDC_SCANBLEND                   1036
#define IDC_3DGLASSES                   1037
#define IDC_USESCANLINES                1038
#define IDC_KEY1                        1039
#define IDC_KEY2                        1040
#define IDC_KEY3                        1041
#define IDC_KEY4                        1042
#define IDC_KEY5                        1043
#define IDC_KEY6                        1044
#define IDC_USEMASK                     1045
#define IDC_FASTMDEC                    1046
#define IDC_FULLVRAM                    1047
#define IDC_FRAMEREAD                   1048
#define IDC_ARATIO                      1049
#define IDC_CLIPBOARD                   1050
#define IDC_CLPEDIT                     1051
#define IDC_QUALTXT                     1052
#define IDC_QUALTXT2                    1053
#define IDC_QUALTXT3                    1054
#define IDC_GARBAGE                     1055
#define IDC_PALTEXWND                   1056
#define IDC_HIRESTEX                    1057
#define IDC_GAMEFIX                     1058
#define IDC_SELFIX                      1059
#define IDC_KEYCONFIG                   1060
#define IDC_T14_STATIC2                 1061
#define IDC_FASTMDEC2                   1062
#define IDC_QUALTXT4                    1063
#define IDC_F14_STATIC3                 1083
#define IDC_F14_STATIC4                 1084
#define IDC_F14_STATIC5                 1085
#define IDC_FIX1                        2038
#define IDC_FIX2                        2039
#define IDC_FIX3                        2040
#define IDC_FIX4                        2041
#define IDC_FIX5                        2042
#define IDC_FIX6                        2043
#define IDC_FIX7                        2044
#define IDC_FIX8                        2045
#define IDC_FIX9                        2046
#define IDC_FIX10                       2047
#define IDC_FIX11                       2048
#define IDC_FIX12                       2049
#define IDC_FIX13                       2050
#define IDC_FIX14                       2051
#define IDC_FIX15                       2052
#define IDC_FIX16                       2053
#define IDC_FIX17                       2054
#define IDC_FIX18                       2055
#define IDC_FIX19                       2056
#define IDC_FIX20                       2057
#define IDC_FIX21                       2058
#define IDC_FIX22                       2059
#define IDC_FIX23                       2060
#define IDC_FIX24                       2061
#define IDC_FIX25                       2062
#define IDC_FIX26                       2063
#define IDC_FIX27                       2064
#define IDC_FIX28                       2065
#define IDC_FIX29                       2066
#define IDC_FIX30                       2067
#define IDC_FIX31                       2068
#define IDC_FIX32                       2069

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        140
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         2070
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
